#import "RefugeRestroomEntity.h"
@implementation RefugeRestroomEntity
@dynamic identifier;
@dynamic name;
@dynamic street;
@dynamic city;
@dynamic state;
@dynamic country;
@dynamic isAccessible;
@dynamic isUnisex;
@dynamic numUpvotes;
@dynamic numDownvotes;
@dynamic ratingNumber;
@dynamic directions;
@dynamic comment;
@dynamic latitude;
@dynamic longitude;
@dynamic createdDate;
@end
